### ISSUE TITLE
Error when processing aborted build

### ISSUE THREAD

**Issue by dmitryAII** [idanmo/jetere#3]
Error when processing aborted build:

Error processing build number 659 for job [Job [id=2, name=system-tests, jenkins_path=dir_system-tests/system-tests]]: IOError - Request for resource: "http://jenkins-master.gspaces.com:8080/job/dir_system-tests/job/system-tests/659/testReport/api/json" status code = 404
Traceback (most recent call last):
  File "/home/dmitry/cloudify-cosmo/jetere/reports/management/commands/sync.py", line 185, in _process_build
    build.number)
  File "/home/dmitry/cloudify-cosmo/jetere/jetere/jenkins.py", line 50, in get_tests_report
    % (resource, response.status_code))
IOError: Request for resource: "http://jenkins-master.gspaces.com:8080/job/dir_system-tests/job/system-tests/659/testReport/api/json" status code = 404

**Comment by dmitryAII** [comment]
Fixed
